@Library('ai-system-design-ci-metrics') _

pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        script {
          parallel(
            linux: {
              metricStage('unit-tests', [os: 'linux', shard: 1]) {
                sh 'echo running linux tests'
              }
              // If you need to emit extra info after the stage:
              // metricEvent('after_stage', [stage_name: 'unit-tests', os: 'linux', note: 'extra metadata'])
            },
            windows: {
              metricStage('unit-tests', [os: 'windows', shard: 1]) {
                bat 'echo running windows tests'
              }
              // If metricStage metadata is not enough for your use case,
              // emit a custom event after stage_end via metricEvent.
            }
          )
        }
      }
    }
  }
}
